# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift

sudo: required

osx_image: 
- xcode10.2


env:
- SCHEME=TaskCommander-Example SWIFT_VERSION=5.0


cache: bundler


before_install:
  - gem update --system
  - gem install bundler
  

script:
  - bundle install
  - bundle exec fastlane test_ci
  - pod lib lint

